import { TWorkers } from "./types/types"

export const MONTHS = [
    { value: "1", label: "Yanvar" },
    { value: "2", label: "Fevral" },
    { value: "3", label: "Mart" },
    { value: "4", label: "Aprel" },
    { value: "5", label: "May" },
    { value: "6", label: "Iyun" },
    { value: "7", label: "Iyul" },
    { value: "8", label: "Avgust" },
    { value: "9", label: "Sentabr" },
    { value: "10", label: "Oktabr" },
    { value: "11", label: "Noyabr" },
    { value: "12", label: "Dekabr" },
  ]

 export const WORKER_STATUS = [ 
    {id:"1", name:"Ish aoliyatida"}, 
    {id:"2", name:"Ta'tilda"}, 
    {id:"3", name:"Mehnat safari"}, 
    {id:"4", name:"Ishdan bo'shatilingan"}, 
  ]
  
export const EDUCATION_STATUS = [ 
  { id:"maktab", name:"Maktab" }, 
  { id:"kollej", name:"Kollej" },
  { id:"texnikum", name:"Texnikum" },
  { id:"bakalavr", name:"Bakalavr" }, 
  { id:"magistr", name:"Magistr" }
]

export const currentYear = new Date().getFullYear()
export const YEARS = Array.from({ length: 10 }, (_, i) => currentYear - i)
export const ITEMS_PER_PAGE = 50;

// export const _facke_workers: TWorkers[] =  [ 
//   { 
//     id: 1,
//     name: "Avazbek Abdullah Majidov muslim",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: "Qoraqalpog'iston respublikasi",
//     region_id: null,
//     region_name: "Samarqand tumani",
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36",
//     passport_series: "AB" 
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "2",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "3",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "4",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "4",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
//   { 
//     id: 1,
//     name: "Avazbek",
//     section_id: null,
//     section_name: null,
//     position_id: "1",
//     position_name: "Dasturchi",
//     birthday: "03.04.2020",
//     phone_youre: "+998991940851",
//     phone_additional: null,
//     phone_work: null,
//     address: null,
//     education: null,
//     education_place: null,
//     photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQadzeS41vONIfTEWPgkhrALgZ31RSwdba_AA&s",
//     passport_number: null,
//     state_id: null,
//     state_name: null,
//     region_id: null,
//     region_name: null,
//     responsible_worker: "Supper admin",
//     status: "1",
//     date: "10.03.2025 11:36" ,
//     passport_series: "AB"
//   }, 
// ]

export type StatusInfo = { color: string, text: string}

export const WORKER_STATUS_INFO = {
  ish_faoliyatida: {
    color:"bg-green-100 text-green-700",
    text:"Ish faoliyatida",
  },
  tatilda: {
    color:"bg-blue-100 text-blue-700",
    text:"Ta'tilda",
  },
  mehnat_safari: {
    color:"bg-yellow-100 text-yellow-700",
    text:"Mahnat safarida",
  },
  ishdan_bushagan: {
    color:"bg-gray-300 text-gray-700",
    text:"Ishdan bo'shagan",
  },
}

export const workerDefaultValues: TWorkers = {
  // id?: number;
  // status?: 0,
  // created_at?: null,
  // responsible_worker?: null,
  birthday: "",
  name: "",
  position_id: 0,
  phone_youre: "",
  section_id:  null,
  address: null,
  education: null,
  education_place: null,
  passport_number: null,
  passport_series: null,
  phone_additional: null,
  phone_work: null,
  photo: null,
  position_name: null,
  region_id:  null,
  region_name: null,
  section_name: null,
  state_id:  null,
  state_name: null,
}

export const DEFAULT_META_DATA = {current_page: 1, from: 1, last_page: 1, links:[], path: "",per_page: 20, to: 1, total: 1}